### ISSUE TITLE
Only seeing 1 plot

### ISSUE THREAD

**Issue by AlStal** [acidbourbon/numpy_ltspice_filter#1]
[Windows example, using filter_demo.py without changes]

Everything is basically working but I _only see one output plot_.  
- It seems to correspond to b2 in the example, regardless of which parameters are used.  
- It seems like parameters are being hard-coded somewhere, because I'm changing "C" and "L" but the plots are always the same.  
- If I use one set of parameters at a time, I can see they get written to param.txt.    

Note: I ran the simulation in LTSpice first, to output the raw file, because the Python script appeared to need it as an input.

![Capture](https://user-images.githubusercontent.com/6247434/69969493-6c604880-1514-11ea-80cb-dd1fb1e6edf8.JPG)

Thanks

**Comment by acidbourbon** [comment]
Hi, thanks a lot for testing it on windows!
When all works as expected, you don't need to run LTspice manually, the modules does that for you.
This is not happening in your case.
Please have a look inside "apply_ltspice_filter.py" line 18:

```
  default_ltspice_command = "C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe -Run -b " 
  if sys.platform == "linux":
    default_ltspice_command = 'wine C:\\\\Program\\ Files\\\\LTC\\\\LTspiceXVII\\\\XVIIx64.exe -Run -b '
```
When the system is identified as linux, then I do a lot of escaping of backspaces when doing the system call to run LTspice with wine. In your case the upper version of the command is executed. Probably there is an issue with the escaping.
For a start, maybe try "C:\\Program Files\\LTC\\LTspiceXVII\\XVIIx64.exe -Run -b " (with double backslashes) and see if it does the trick. I don't know how the windows command line handles escape characters and backslashes ... would be cool if you could do some research there and let us know how to best call LTspice from the command line.

Regards,
Micha

**Comment by acidbourbon** [comment]
Someone wrote me a comment in my blog, claiming to have fixed it under windows. Can you pull the newest version from GitHub and try again?

**Comment by AlStal** [comment]
Tried latest and it's fixed.  The Windows path is now simplified, and no longer has all the extra escape characters.  Closed!

**Comment by acidbourbon** [comment]
Hey, thank you for testing. This has been my first ticket on GitHub. ;) . Uuuh, special!All the bestMichaVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: AlStal <notifications@github.com> Datum: 04.12.19  18:31  (GMT+01:00) An: acidbourbon/numpy_ltspice_filter <numpy_ltspice_filter@noreply.github.com> Cc: Michael Wiebusch <stratomaster@gmx.net>, Comment <comment@noreply.github.com> Betreff: Re: [acidbourbon/numpy_ltspice_filter] Only seeing 1 plot (#1) Tried latest and it's fixed.  The Windows path is now simplified, and no longer has all the extra escape characters.  Closed!

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/acidbourbon/numpy_ltspice_filter/issues/1?email_source=notifications\u0026email_token=AA6E4MQ3VWYZEWFA6KCGKSTQW7SPNA5CNFSM4JTXENWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEF53PIY#issuecomment-561756067",
"url": "https://github.com/acidbourbon/numpy_ltspice_filter/issues/1?email_source=notifications\u0026email_token=AA6E4MQ3VWYZEWFA6KCGKSTQW7SPNA5CNFSM4JTXENWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEF53PIY#issuecomment-561756067",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
